name: groundingbooth
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.12.12
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.8.18
  - readline=8.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - accelerate==0.23.0
      - addict==2.4.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - albumentations==0.4.3
      - aliyun-python-sdk-core==2.14.0
      - aliyun-python-sdk-kms==2.16.2
      - altair==5.0.1
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.0
      - appdirs==1.4.4
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.4.1
      - async-timeout==4.0.2
      - attrs==23.1.0
      - autobahn==23.1.2
      - automat==22.10.0
      - backcall==0.2.0
      - backports-zoneinfo==0.2.1
      - beautifulsoup4==4.12.2
      - bitarray==2.7.5
      - black==23.10.1
      - bleach==6.0.0
      - blinker==1.6.2
      - blis==0.7.9
      - braceexpand==0.1.7
      - brotlipy==0.7.0
      - cachetools==5.3.1
      - catalogue==2.0.8
      - cchardet==2.1.7
      - certifi==2022.12.7
      - cffi==1.16.0
      - cfgv==3.3.1
      - chardet==5.1.0
      - charset-normalizer==2.1.1
      - click==8.1.3
      - clip==1.0
      - cloudpickle==2.2.1
      - cmake==3.25.0
      - colorama==0.4.6
      - comm==0.1.3
      - confection==0.0.4
      - constantly==23.10.4
      - contexttimer==0.3.3
      - contourpy==1.1.0
      - crcmod==1.7
      - cryptography==42.0.3
      - cycler==0.11.0
      - cymem==2.0.7
      - cython==0.29.35
      - datasets==2.12.0
      - debugpy==1.6.7
      - decorator==5.1.1
      - decord==0.6.0
      - defusedxml==0.7.1
      - diffusers==0.21.0.dev0
      - dill==0.3.6
      - distlib==0.3.6
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - dpcpp-cpp-rt==2024.0.2
      - einops==0.6.1
      - exceptiongroup==1.1.1
      - executing==2.0.1
      - fairscale==0.4.4
      - fancycompleter==0.9.1
      - fastapi==0.110.1
      - fastjsonschema==2.17.1
      - ffmpy==0.3.2
      - filelock==3.13.1
      - fonttools==4.40.0
      - fqdn==1.5.1
      - frozenlist==1.3.3
      - fsspec==2023.10.0
      - ftfy==6.1.1
      - future==0.18.3
      - fvcore==0.1.5.post20221221
      - gdown==4.7.1
      - gitdb==4.0.10
      - gitpython==3.1.31
      - google-auth==2.19.1
      - google-auth-oauthlib==1.0.0
      - gradio==3.16.0
      - grpcio==1.54.2
      - h11==0.14.0
      - hkdf==0.0.3
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.16.4
      - humanize==4.9.0
      - hydra==2.5
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - hyperlink==21.0.0
      - identify==2.5.24
      - idna==3.4
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.2
      - imgaug==0.2.6
      - importlib-metadata==6.6.0
      - importlib-resources==5.12.0
      - incremental==22.10.0
      - intel-cmplr-lib-rt==2024.0.2
      - intel-cmplr-lic-rt==2024.0.2
      - intel-opencl-rt==2024.0.2
      - intel-openmp==2024.0.2
      - iopath==0.1.9
      - ipykernel==6.24.0
      - ipython==8.12.2
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.6
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - jmespath==0.10.0
      - joblib==1.3.1
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==8.2.0
      - jupyter-console==6.6.3
      - jupyter-core==5.7.1
      - jupyter-events==0.6.3
      - jupyter-server==2.6.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==3.0.7
      - kaggle==1.5.13
      - kiwisolver==1.4.4
      - kornia==0.5.8
      - langcodes==3.3.0
      - lazy-loader==0.2
      - lightning-utilities==0.9.0
      - linkify-it-py==2.0.3
      - lit==15.0.7
      - lvis==0.5.3
      - lxml==4.9.2
      - magic-wormhole==0.13.0
      - markdown==3.4.3
      - markdown-it-py==2.2.0
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mdit-py-plugins==0.4.0
      - mdurl==0.1.2
      - mistune==2.0.5
      - mkl==2024.0.0
      - mkl-fft==1.3.6
      - mkl-service==2.4.0
      - mmcv==2.1.0
      - mmengine==0.10.3
      - model-index==0.1.11
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.14
      - murmurhash==1.0.9
      - mypy-extensions==1.0.0
      - nbclassic==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.5.0
      - nbformat==5.9.0
      - nest-asyncio==1.6.0
      - networkx==3.1
      - ninja==1.11.1
      - nltk==3.8.1
      - nodeenv==1.8.0
      - notebook==6.5.4
      - notebook-shim==0.2.3
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.2.140
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - open-clip-torch==2.20.0
      - opencv-python==4.7.0.72
      - opencv-python-headless==4.5.5.64
      - opendatalab==0.0.10
      - opendatasets==0.1.22
      - openmim==0.3.9
      - openxlab==0.0.34
      - ordered-set==4.1.0
      - orjson==3.10.0
      - oss2==2.17.0
      - overrides==7.3.1
      - packaging==23.2
      - pandas==2.0.2
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathspec==0.11.2
      - pathtools==0.1.2
      - pathy==0.10.2
      - pdbpp==0.10.3
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==9.4.0
      - pipreqs==0.4.13
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.11.0
      - plotly==5.15.0
      - portalocker==2.7.0
      - pre-commit==3.3.3
      - preshed==3.0.8
      - prometheus-client==0.17.0
      - prompt-toolkit==3.0.43
      - protobuf==3.20.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pudb==2019.2
      - pure-eval==0.2.2
      - pyarrow==12.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.6
      - pycparser==2.21
      - pycryptodome==3.20.0
      - pydantic==1.10.9
      - pydeck==0.8.1b0
      - pydeprecate==0.3.1
      - pydub==0.25.1
      - pygments==2.17.2
      - pympler==1.0.1
      - pynacl==1.5.0
      - pyopenssl==24.0.0
      - pyparsing==3.0.9
      - pyre-extensions==0.0.29
      - pyrepl==0.9.0
      - pyrsistent==0.19.3
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - python-magic==0.4.27
      - python-multipart==0.0.9
      - python-slugify==8.0.1
      - pytorch-fid==0.3.0
      - pytorch-lightning==1.4.2
      - pytorch-triton==0.0.1
      - pytz==2023.3
      - pytz-deprecation-shim==0.1.0.post0
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - pyzmq==25.1.0
      - qtconsole==5.4.3
      - qtpy==2.3.1
      - regex==2023.10.3
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - responses==0.18.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.4.2
      - rsa==4.9
      - sacrebleu==2.3.1
      - safetensors==0.3.3
      - salesforce-lavis==1.0.0
      - scikit-image==0.20.0
      - scipy==1.9.1
      - seaborn==0.12.2
      - send2trash==1.8.2
      - sentencepiece==0.1.99
      - sentry-sdk==1.25.1
      - service-identity==23.1.0
      - setproctitle==1.3.2
      - setuptools==60.2.0
      - shapely==2.0.1
      - six==1.16.0
      - smart-open==6.3.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - spacy==3.5.3
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.4
      - spake2==0.8
      - srsly==2.4.6
      - stack-data==0.6.3
      - starlette==0.37.2
      - streamlit==1.23.1
      - submitit==1.4.5
      - sympy==1.12
      - tabulate==0.9.0
      - tbb==2021.11.0
      - tenacity==8.2.2
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.0
      - termcolor==2.3.0
      - terminado==0.17.1
      - test-tube==0.7.5
      - text-unidecode==1.3
      - thinc==8.1.10
      - tifffile==2023.4.12
      - timm==0.4.12
      - tinycss2==1.2.1
      - tokenizers==0.13.3
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.0
      - torch==2.0.1
      - torch-fidelity==0.3.0
      - torchmetrics==0.5.0
      - torchvision==0.15.2
      - tornado==6.3.2
      - tqdm==4.65.2
      - traitlets==5.14.1
      - transformers==4.27.0
      - triton==2.0.0
      - twisted==23.10.0
      - txaio==23.1.1
      - txtorcon==23.11.0
      - typer==0.7.0
      - typing-extensions==4.11.0
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - tzlocal==4.3
      - uc-micro-py==1.0.3
      - ultralytics==8.0.119
      - uri-template==1.2.0
      - urllib3==1.26.18
      - urwid==2.1.2
      - uvicorn==0.29.0
      - validators==0.20.0
      - virtualenv==20.23.1
      - wandb==0.15.4
      - wasabi==1.1.2
      - watchdog==3.0.0
      - wcwidth==0.2.13
      - webcolors==1.13
      - webdataset==0.2.48
      - webencodings==0.5.1
      - websocket-client==1.5.3
      - websockets==12.0
      - werkzeug==2.3.4
      - widgetsnbextension==4.0.7
      - wmctrl==0.5
      - xformers==0.0.20
      - xxhash==3.2.0
      - yacs==0.1.8
      - yapf==0.40.2
      - yarg==0.1.9
      - yarl==1.9.2
      - zipp==3.15.0
      - zope-interface==6.1
